name: AuthYou
version: 1.0
main: de.mreturkey.authyou.AuthYou
author: mReTurkey
description: AuthYou - A lightweight and performance-friendly Authentication Plugin
commands:
  login:
    usage: /login
    aliases: l
    description: Login to the server
  register:
    usage: /register
    description: Register to server
  logout:
    usage: /logout
    description: Logout you from the server